//get all users
GET http://localhost:3001/users

###
//get single user
GET http://localhost:3001/users/2

###
//create user
POST http://localhost:3001/users
Content-Type: application/json

{
    "username" : "reza3",
    "email" : "reza3@gmail.com",
    "password" : "123",
    "confirmPassword" : "123",
    "role" : "user"
}

###
//create Admin
POST http://localhost:3001/users
Content-Type: application/json

{
    "username" : "admin",
    "email" : "admin@gmail.com",
    "password" : "123",
    "confirmPassword" : "123",
    "role" : "admin"
}
###
//update User
PATCH  http://localhost:3001/users/4
Content-Type: application/json

{
    "username" : "rezaaja",
    "email" : "rezaaja@gmail.com",
    "password" : "",
    "confirmPassword" : "",
    "role" : "user"
}
###
//hapus user
DELETE  http://localhost:3001/users/4

###
//Login admin
POST http://localhost:3001/login
Content-Type: application/json

{
    "email" : "admin@gmail.com",
    "password" : "123"
}
###
//Login user
POST http://localhost:3001/login
Content-Type: application/json

{
    "email" : "dimas@gmail.com",
    "password" : "123456"
}

###
//Me
GET http://localhost:3001/me

###
//Logout
DELETE  http://localhost:3001/logout

###
//get all data kriteria
GET http://localhost:3001/kriteria

###
//get all data alternatif
GET http://localhost:3001/alternatif

###
//get all data Hasil
GET http://localhost:3001/hasil

###
//get all data Jalur
GET http://localhost:3001/jalur

###
//get all data Nilai Alternatif
GET http://localhost:3001/nilai_alternatif

###
//POST data Alternatif
POST http://localhost:3001/alternatif
Content-Type: application/json

{
    "kode_alternatif":"A1",
    "nama_alternatif":"Reza",
    "nama_jalur":"Zonasi"
}
###
//POST data Jalur
POST http://localhost:3001/jalur
Content-Type: application/json

{
    "kode_jalur":"J1",
    "nama_jalur":"Zonasi"
}
###
//POST data Kriteria
POST http://localhost:3001/kriteria
Content-Type: application/json

{
    "kode_kriteria":"C3",
    "nama_kriteria":"Usia",
    "bobot_kriteria":0.2

}
###
//Edit data Kriteria
PATCH http://localhost:3001/kriteria/1
Content-Type: application/json

{
    "kode_kriteria":"C1",
    "nama_kriteria":"Jarak",
    "bobot_kriteria":0.5

}
###
//POST data Nilai alternatif
POST http://localhost:3001/nilai_alternatif
Content-Type: application/json

{
    "nama_alternatif":"Nibros",
    "nama_kriteria":"Nilai Rapot",
    "nilai_real":86.5,
    "nilai_fuzzy":3,
    "keterangan":"Baik"
}

###
//EDIT data Nilai alternatif
PATCH http://localhost:3001/nilai_alternatif/2
Content-Type: application/json

{
    "nama_alternatif":"Rifki",
    "nama_kriteria":"Nilai Rapot",
    "nilai_real":82.5,
    "nilai_fuzzy":3,
    "keterangan":"Baik"
}

###
//get Nilai Alternatif by Id
GET http://localhost:3001/nilai_alternatif/5

###
//get all data Hasil
GET http://localhost:3001/hasil

###
//POST data Hasil
POST http://localhost:3001/hasil

